### PR TITLE
update code, handle problem in splitting

### PR DESCRIPTION
**Pull request by LinguList**
This makes the data more apt for automated sequence comparison

### CODE REVIEW

**Comment by tresoldi** [comment]
Ok, you were covering the problematic form as well, I missed the email for reviewing it.

**Comment by LinguList** [comment]
I don't know what changes you request @tresoldi, but please submit them yourself, as it was not clear from the message.

**Comment by tresoldi** [comment]
@LinguList `.split_forms()` splits the forms in order to feed them to the tokenizer (here, getting `ipa`), but it does not change `form` itself, so that the `.strip()` you added only propagates to `ipa`.

My solution would be to do it "by hand", either when extracting the data (i.e., `row[cid]`) or when passing the value to `.add_lexemes()`, but this is the kind of data manipulation that we are supposed to avoid...

**Comment by tresoldi** [comment]
I guess it should be in `.clean_form()`?

**Comment by LinguList** [comment]
Yes, clean_form needs to be adjusted, but note that my split_forms was also handling the issue, as you will be able to see that the "+" at the end of the words disappeared, which caused problems, as lingpy complains: `m a t +` does not make sense, but should be `m a t`. If there's another issue now, this is not only related to the stripping, which is basiclly handlign this first problem of trailing plusses.

**Comment by LinguList** [comment]
In fact, the newline was already in the data, so this error is on the data, so the error is not due to my changes. The problem is that newline is deleterious for lingpy when writing data, so it would best be removed by us when creating the cldf file. So this would mean: replace newline by space in the script. No big deal, in fact, and still "true to the value" as this was no intended by the authors

**Comment by tresoldi** [comment]
That is not the issue: the output of `.clean_form()` and `.split_forms()` is only used for the segments, not for the value. If we override the default `.clean_form()` with one which always returns "abc", the values in `forms.csv` wil lbe the correct one, only the segments will be changed. pylexibank does write the newline between quotes, but this is not good.

I will call strip when adding lexemes, for the time being, let me know if there is a recommended way to clean value (@xrotwang , @SimonGreenhill , and @chrzyki as well).

**Comment by tresoldi** [comment]
Fixed with c174264 , we can always get back to the discussion in an issue.

**Comment by LinguList** [comment]
>  Fixed with c174264 , we can always get back to the discussion in an issue.

could you take the chance and also clean the useless creation of ipa, etc., to stick to what we discussed?

**Pull request merged**
